tables:
  - name: persons
    count: 10
    columns:
      - name: person_id
        type: range
        processor:
          type: int
          from: 1
          step: 1
      - name: email
        type: gen
        processor:
          template: '{{Email}}'
      - name: salary
        type: rand
        processor:
          type: float64
          low: 2000.0
          high: 5000.0
          format: '%.2f'
      - name: fake_name
        type: expr
        processor:
          expression: fakeit('name', {})
      - name: fake_email
        type: expr
        processor:
          expression: fakeit('email', {})
      - name: fake_phone
        type: expr
        processor:
          expression: fakeit('phone', {})
      - name: fake_sentence
        type: expr
        processor:
          expression: > 
            fakeit('sentence', {'wordCount': 5})
      - name: fake_number
        type: expr
        processor:
          expression: >
            fakeit('number', {'min': 1, 'max': 100})
  - name: billing
    count: 10
    columns:
      - name: billing_id
        type: range
        processor:
          type: int
          from: 1
          step: 1
      - name: installments
        type: rand
        processor:
          type: int
          low: 2
          high: 12
      - name: due_amount
        type: rand
        processor:
          type: float64
          low: 1000.0
          high: 2000.0
          format: '%.2f'
      - name: installment_value
        type: expr
        processor:
          expression: float(due_amount) / int(installments)
          format: '%.4f'
      - name: max_loan
        type: expr
        processor:
          expression: float(match('persons','person_id', billing_id, 'salary')) / 0.3
          format: '%.2f'
      - name: ranged
        type: expr
        processor:
          expression: 1..12 # will stop at 10 due to table count
      - name: random_value
        type: expr
        processor:
          expression: rand()
      - name: random_range
        type: expr
        processor:
          expression: rand_range(-10, int(installments))
      - name: min_value
        type: expr
        processor:
          expression: min(5,-3,0.3,7,-0.5, int(installments))
      - name: max_value
        type: expr
        processor:
          expression: max(5,-3,0.3,7,-0.5, int(installments))
  - name: contracts
    count: 3
    columns:
      - name: id
        type: range
        processor:
          type: int
          from: 1
          step: 1
      - name: name
        type: expr
        processor:
          expression: fakeit('name', {})
      - name: enroll
        type: expr
        processor:
          expression: add_date(0, 0, row_number, '2023-08-14')
          format: '2006-01-02'
      - name: months
        type: rand
        processor:
          type: int
          low: 2
          high: 5
