tables:
  - name: persons
    count: 100
    columns:
      - name: person_id
        type: range
        processor:
          type: int
          from: 1
          step: 1
      - name: age
        type: rand
        processor:
          type: int
          low: 16
          high: 80
      - name: gender
        type: gen
        processor:
          value: ${gender}
      - name: greeting
        type: case
        processor:
          - when: int(age) <= 5 && gender == 'male'
            then: 'Little guy'
          - when: int(age) <= 5 && gender == 'female'
            then: 'Little girl'
          - when: int(age) > 5 && int(age) <= 10 && gender == 'male'
            then: 'Buddy'
          - when: int(age) > 5 && int(age) <= 10 && gender == 'female'
            then: 'Sweetie'
          - when: int(age) > 10 && int(age) <= 15 && gender == 'male'
            then: "'Hey, young man'"
          - when: int(age) > 10 && int(age) <= 15 && gender == 'female'
            then: "'Hey, young lady'"
          - when: int(age) > 15 && int(age) <= 20 && gender == 'male'
            then: "'Whats up, dude?'"
          - when: int(age) > 15 && int(age) <= 20 && gender == 'female'
            then: "'Whats up, girl?'"
          - when: int(age) > 20 && int(age) <= 30 && gender == 'male'
            then: "'Hey, man'"
          - when: int(age) > 20 && int(age) <= 30 && gender == 'female'
            then: "'Hey, there'"
          - when: int(age) > 30 && int(age) <= 40 && gender == 'male'
            then: "'Hello, mister'"
          - when: int(age) > 30 && int(age) <= 40 && gender == 'female'
            then: "'Hello, madam'"
          - when: int(age) > 40 && gender == 'male'
            then: "'Good to see you, sir'"
          - when: int(age) > 40 && gender == 'female'
            then: "'Good to see you, madam'"
